<?php
    require_once 'inc/config.php';

    echo "<h1>Categories</h1>";
    $categoriesList = array();
    for ($i = 0; $i < 100; $i++){
        array_push($categoriesList, readProductCategories($url, $accessToken, $i));
        //Wait 100ms
        usleep(100000);
    }

    //Write categories to file
    $fp = fopen('inc/categories.json', 'w');
    fwrite($fp, serialize($categoriesList));
    fclose($fp);

    echo "<pre>";
    var_dump($categoriesList);
    echo "</pre>";

    
    

    function readProductCategories($url, $accessToken, $page){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url . '/v2/products/categories?page=' . $page);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
    }