<?php
    require_once 'inc/config.php';

    echo "<h1>Brands</h1>";
    $brandList = readProductCategories($url, $accessToken);
    echo "<pre>";
    var_dump($brandList);
    echo "</pre>";

    
    //Use https://www.convertcsv.com/json-to-csv.htm to convert brand list to csv
    function readProductCategories($url, $accessToken){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url . '/v2/products/brands');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $file = 'inc/brands.json';
        //Write upload id to file
        file_put_contents($file, $result);

        return json_decode($result, true);    
    }