<?php
   function postDHLRetoure($sandbox, $dhl_base64, $dhl_api_base64, $receiver_id, $order_data){
      // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
      $ch = curl_init();

      $requestUrl = 'https://cig.dhl.de/services/production/rest/returns/';
      if($sandbox){ $requestUrl = 'https://cig.dhl.de/services/sandbox/rest/returns/'; }

      $xml = generateRetoureXML($receiver_id, $order_data);

      curl_setopt($ch, CURLOPT_URL, $requestUrl);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_POST, 1);
      curl_setopt($ch, CURLOPT_POSTFIELDS, $xml);


      $headers = array();
      $headers[] = 'Accept: application/json';
      $headers[] = 'Authorization: Basic ' . $dhl_api_base64;
      $headers[] = 'Dpdhl-User-Authentication-Token: ' . $dhl_base64;
      $headers[] = 'Content-Type: application/xml';
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

      $result = curl_exec($ch);
      if (curl_errno($ch)) {
          echo 'Error:' . curl_error($ch);
      }
      curl_close($ch);


      $json = json_decode($result, true);

      //var_dump, when error
      if(!isset($json["shipmentNumber"])){
         var_dump($result);
      }
      
      return $json["shipmentNumber"];
  }



   //TODO Country
   function generateRetoureXML($receiver_id, $order_data){
      $xml = '<?xml version="1.0" encoding="UTF-8"?>
      <ReturnOrder>
         <receiverId>' . $receiver_id . '</receiverId>
         <customerReference>' . $order_data["orderNumber"] . '</customerReference>
         <senderAddress>
            <name1>' . $order_data["deliveryAddress"]["firstName"] . " " . $order_data["deliveryAddress"]["lastName"] . '</name1>
            <name2></name2>
            <name3></name3>
            <streetName>' . $order_data["deliveryAddress"]["street"] . '</streetName>
            <houseNumber>' . $order_data["deliveryAddress"]["houseNumber"] . '</houseNumber>
            <postCode>' . $order_data["deliveryAddress"]["zipCode"] . '</postCode>
            <city>' . $order_data["deliveryAddress"]["city"] . '</city>
            <country>
               <countryISOCode>DE</countryISOCode>
            </country>
         </senderAddress>
         <email>maik.riedlsperger@loechel-industriebedarf.de</email>
         <returnDocumentType>SHIPMENT_LABEL</returnDocumentType>
      </ReturnOrder>';

      $xml = preg_replace('/\t+/', ' ', $xml); //Remove tab
      $xml = str_replace('\\r\\n', ' ', $xml); //Remove line breaks
      return $xml;
   }

   function generateRetoureXMLTest($receiver_id){
      $xml = '<?xml version="1.0" encoding="UTF-8"?>
      <ReturnOrder>
         <receiverId>' . $receiver_id . '</receiverId>
         <customerReference>2219820821</customerReference>
         <shipmentReference>cbn4bggmw3</shipmentReference>
         <senderAddress>
            <name1>Wolfgang Rodriguez</name1>
            <name2></name2>
            <name3></name3>
            <streetName>Am Erlenborn</streetName>
            <houseNumber>14</houseNumber>
            <postCode>63633</postCode>
            <city>Birstein</city>
            <country>
               <countryISOCode>DE</countryISOCode>
            </country>
         </senderAddress>
         <email>maik.riedlsperger@loechel-industriebedarf.de</email>
         <returnDocumentType>SHIPMENT_LABEL</returnDocumentType>
      </ReturnOrder>';

      $xml = preg_replace('/\t+/', ' ', $xml); //Remove tab
      $xml = str_replace('\\r\\n', ' ', $xml); //Remove line breaks
      return $xml;
   }