<?php
    require_once 'inc/config.php';

    //Check, if the csv file was already processed
    if(file_exists($csvPathOrders)){
		echo $now." CSV file was not processed yet!";
	}
    else{
        //Read date of last operation
        $lastDate =  file_get_contents('inc/lastDate.txt');

        //Check if new orders exist
        $orders = getOrders($url, $accessToken, $lastDate);

        //Write orders and last date to file. Display error message, if there are no new orders
        if(convertOrdersToCsv($orders) == null){
            echo "No new orders...";
        }
        else{
            writeLastDate();
        }
    }

    


    
    function getOrders($url, $accessToken, $lastDate){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        $requestUrl = $url . '/v4/orders?fromDate' . $lastDate;
        echo $requestUrl;

        curl_setopt($ch, CURLOPT_URL, $requestUrl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        logMe($result);

        return json_decode($result, true);
    }



    /*
    * Format
    * Bestellnr [0]; Bestelldatum [1]; E-Mail [2]; Artikelnr [3]; Menge[4]; Preis [5]; 
    * V-Firma1 [6]; V-Strasse [7]; V-Firma2 [8]; V-PLZ [9]; V-Ort [10]; V-LKZ [11]; 
    * L-Firma1 [12]; L-Strasse [13]; L-Firma2 [14]; L-PLZ [15]; L-Ort [16]; L-LKZ [17]; 
    * Telefonnr [18]; Zahlungsart [19]; Zahlungsnr [20]; Porto [21]; Nebenkosten [22];
    * LastModified [23]
    */
    function convertOrdersToCsv($orders){
        echo generateHeadline();
        if(count($orders) == 1){
            return null;
        }
        else{
            $csv = "";

            foreach($orders["resources"] as &$value){
                foreach($value["positionItems"] as &$item){
                    $csv .= $value["orderNumber"];
                    $csv .= $value["orderDate"];
                    $csv .= ''; //Mail
                    $csv .= $item["product"]["sku"];
                    $csv .= ''; //MENGE???
                    $csv .= $item["itemValueGrossPrice"]["amount"];
                    //Versand
                    //Rechnung
                    $csv .= ''; //Telefonnr
                    $csv .= $value["payment"]["paymentMethod"];
                    $csv .= $value["salesOrderId"];
                    $csv .= $value["initialDeliveryFees"]["deliveryFeeAmount"]["amount"];
                    $csv .= '0'; //TODO Nebenkosten
                    $csv .= $value["lastModifiedDate"];
                }    
            }
        }
    }



    function generateHeadline(){
        return 'Bestellnr [0]; Bestelldatum [1]; E-Mail [2]; Artikelnr [3]; Menge[4]; 
        Preis [5]; V-Firma1 [6]; V-Strasse [7]; V-Firma2 [8]; V-PLZ [9]; 
        V-Ort [10]; V-LKZ [11]; L-Firma1 [12]; L-Strasse [13]; L-Firma2 [14]; 
        L-PLZ [15]; L-Ort [16]; L-LKZ [17]; Telefonnr [18]; Zahlungsart [19]; 
        Zahlungsnr [20]; Porto [21]; Nebenkosten [22]';
    }



    function writeLastDate(){
        $file = 'inc/lastDate.txt';
        //Write upload id to file
        file_put_contents($file, getCurrentDateTimeOtto());
    }