<?php
    require_once 'inc/config.php';

    $csv = "ARTNR;MOIN;ErrorCode"  . PHP_EOL;

    $page = 0;
    do{
        $restricted = getRestrictedProducts($url, $accessToken, $page);
        foreach($restricted["marketPlaceStatus"] as &$value){
            $csv .= $value["sku"] . ";" . $value["moin"] . ";" . $value["errors"][0]["code"] . PHP_EOL;
        }

        logMe("Restricted page:" . $page);

        $page++;
    } while (sizeof($restricted["marketPlaceStatus"]) === 100);
    

    $file = 'inc/restricted.csv';
    //Write csv to file
    file_put_contents($file, $csv);

    

    




    function getRestrictedProducts($url, $accessToken, $page){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url . '/v2/products/marketplace-status?marketPlaceStatus=RESTRICTED&page=' . $page);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
    }