<?php


    require_once 'inc/config.php';


    
    echo "<h1>Product Info</h1>";
    $sku = "2019560421";
    $productInfo = readSingleProduct($url, $accessToken, $sku);
    echo "<pre>";
    var_dump($utaskResult);
    echo "</pre>";








    function readSingleProduct($url, $accessToken, $sku){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url . '/v2/products/' . $sku);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
    }




