<?php
    require_once 'inc/config.php';

    $sku = $_GET["sku"];
    
    echo "<h1>Marketplace Info</h1>";
    $marketplaceInfo = readMarketplaceStatus($url, $accessToken, $sku);
    echo "<pre>";
    var_dump($marketplaceInfo);
    echo "</pre>";

    
    echo "<h1>Product Info</h1>";
    $productInfo = readSingleProduct($url, $accessToken, $sku);
    echo "<pre>";
    var_dump($productInfo);
    echo "</pre>";

    








    function readSingleProduct($url, $accessToken, $sku){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url . '/v2/products/' . $sku);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
    }


    function readMarketplaceStatus($url, $accessToken, $sku){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url . '/v2/products/' . $sku . '/marketplace-status');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
    }




