<?php
    require_once 'inc/config.php';

    $target_dir = "uploads/";
    $target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]);
    // Check if image file is a actual image or fake image
    if(isset($_POST["submit"])) {
        if (move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $target_file)) {
            $filename = htmlspecialchars(basename( $_FILES["fileToUpload"]["name"]));
            echo "Die Datei ". $filename . " wurde hochgeladen!<br><br>";

            $postfields = readShipmentsFromCsv($target_file);    

            $shipments = createNewShipments($url, $accessToken, $postfields);

            logMe($shipments);
            if(isset($shipments["errors"])){
                logMe($postfields);
            } 

            logMe(getTodaysShipments($url, $accessToken));
          } else {
            echo "Fehler beim Upload...";
          }
    }





    function createNewShipments($url, $accessToken, $postfields){
        $json = JSONfyPostfields($postfields, "tracking");

        //Remove first and last char
        $json = substr($json, 1);
        $json = substr_replace($json, "", -1);  
        

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url . '/v1/shipments');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $json);

        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
    }






    /*
    * Format:
    * Carrier [0]; TrackingNumber[1]; PositionItemId [2]; SalesOrderId[3]
    */
    function readShipmentsFromCsv($csvPath){
        $postfields = array();

        if (($handle = fopen($csvPath, "r")) !== FALSE) {
            fgetcsv($handle); //Skip first line
            while (($data = fgetcsv($handle, 0, ";")) !== FALSE) {
                echo $data[0] . ";" . $data[1] . ';' . $data[2] . ';' . $data[3];

                array_push($postfields, generateShipmentJson($data[0], $data[1], $data[2], $data[3], $data[4]));
            }
            fclose($handle);
        } else {
            echo "Fehler beim Lesen der Datei...";
        } 

        return $postfields;
    }







    function generateShipmentJson($carrier, $trackingNumber, $positionItemId, $salesOrderId, $returnNumber){
        $json = '{
            "trackingKey":{
                "carrier":"' . $carrier . '",
                "trackingNumber":"' . $trackingNumber . '"
            },
            "shipDate":"' . getCurrentDateTimeOtto() . '",
            "shipFromAddress":{
                "city":"Sulingen",
                "countryCode":"DEU",
                "zipCode":"27232"
            },
            "positionItems":[{
                "positionItemId":"' . $positionItemId . '",
                "salesOrderId":"' . $salesOrderId . '",
                "returnTrackingKey": {
                    "carrier": "DHL",
                    "trackingNumber": "' . $returnNumber . '0"
                }
            }]
        }';

        return $json;
    }







    function getTodaysShipments($url, $accessToken){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        $requestUrl = $url . '/v1/shipments?datefrom=' . date('Y-m-d');
        echo $requestUrl;

        curl_setopt($ch, CURLOPT_URL, $requestUrl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $accessToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
    }