<a href="index.php"><button>Home</button></a><br><br><br>

<?php
    $username = "api_0815";
    $password = "NormalSummonAleister";
    $sandbox = false;

    $csvPathOrders = '../OttoOrders.csv';

    $url = "https://api.otto.market";
    if($sandbox){
        $url = "https://sandbox.api.otto.market";
    }

    $accessToken = getAccessToken($url, $username, $password);	








    function getAccessToken($url, $username, $password){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url . '/v1/token');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "username=".$username."&password=".$password."&grant_type=password&client_id=token-otto-api");

        $headers = array();
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        $headers[] = 'Cache-Control: no-cache';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true)["access_token"];
	}






    function logMe($log){
        //Dump log to gui
        echo "<pre>";
        var_dump($log);
        echo "</pre>";

        //Write log to file
        $myfile = file_put_contents('inc/log.log', getCurrentDateTimeOtto() . PHP_EOL . serialize($log).PHP_EOL.PHP_EOL , FILE_APPEND | LOCK_EX);
    }


    /*
    * Returns the current DateTime in a format, that Otto accepst.
    * date(DateTime::ISO8601) won't work, because it's missing milliseconds.
    *
    * @return   DateTime    Current date+time
    */
    function getCurrentDateTimeOtto(){
        return date("Y-m-d\TH:i:s.000+0100");
    }